# This workflow will create and populate a new DB every time a CSV dataset will committed

name: Create and populate a DB from CSV tables

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    # /!\ Set your branch name /!\
    branches: ['syncdb']
    paths: 
      - 'dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv'
      - 'dati-province/dpc-covid19-ita-province.csv'
      - 'dati-regioni/dpc-covid19-ita-regioni.csv'
      - 'note/dpc-covid19-ita-note-*.csv'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DB_PATH: database/dpc-covid19-ita_db.sqlite3
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Install scripts dependency
    - name: Install sqlite
      run: sudo apt-get install sqlite3
    - name: Install csvkit
      run: |
        sudo pip install csvkit
    # Runs commands using the runners shell
    - name: Run the db_build bash script
      run: |
        sh ./scripts/db_build.sh
    - name: Run the db_populate bash script
      run: |
        sh ./scripts/db_populate.sh      
    - name: Commit files  # transfer the new DB files back into the repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./database
        git commit -m "[GH Actions] Updating the repository's DB file in the database folder"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        # /!\ Set your branch name /!\
        branch: 'syncdb'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true